### PR TITLE
Update rb-sys to 0.9.102 for ruby 3.4 compatibility

### PR DESCRIPTION
**Pull request by casperisfine**
Otherwise it fails with:

```
LoadError: /tmp/bundle/ruby/3.4.0+0/gems/tiktoken_ruby-0.0.8/lib/tiktoken_ruby/tiktoken_ruby.so:
undefined symbol: ruby_abi_version - ruby_abi_version (LoadError)
```

~~However compilation is now failing with:~~

```
error[E0609]: no field `len` on type `RString__bindgen_ty_1__bindgen_ty_1`
   --> /Users/byroot/.cargo/registry/src/index.crates.io-6f17d22bba15001f/magnus-0.4.4/src/r_string.rs:366:57
    |
366 |             slice::from_raw_parts(h.ptr as *const u8, h.len as usize)
    |                                                         ^^^ unknown field
    |
    = note: available fields are: `ptr`, `aux`

error[E0609]: no field `len` on type `RString__bindgen_ty_1__bindgen_ty_1`
   --> /Users/byroot/.cargo/registry/src/index.crates.io-6f17d22bba15001f/magnus-0.4.4/src/r_string.rs:954:19
    |
954 |                 h.len as usize
    |                   ^^^ unknown field
    |
    = note: available fields are: `ptr`, `aux`

error[E0609]: no field `len` on type `RString__bindgen_ty_1__bindgen_ty_2`
   --> /Users/byroot/.cargo/registry/src/index.crates.io-6f17d22bba15001f/magnus-0.4.4/src/r_string.rs:996:44
    |
996 |     value.as_internal().as_ref().as_.embed.len
    |                                            ^^^ unknown field
    |
    = note: available field is: `ary`

For more information about this error, try `rustc --explain E0609`.
```

~~Which I don't know how to fix. @ianks could you lend me a hand here?~~

### CODE REVIEW

**Comment by casperisfine** [comment]
Nevermind, the compilation failure was because I forgot to rebase my fork 🤦

**Comment by casperisfine** [comment]
Hum, seems like there's no version of rb-sys compatible with both 3.4 and 2.7?

**Comment by ianks** [comment]
> Hum, seems like there's no version of rb-sys compatible with both 3.4 and 2.7?

`rb-sys` is [(painfully) compatible down to 2.6](https://github.com/oxidize-rb/rb-sys/blob/086d3a2a2992b66c4b84eacad7c7a92bf67725b5/data/toolchains.json#L3)

I think this error is a bundler issue?

```
  	There are no versions of bundler (= 2.5.18) compatible with your Ruby & RubyGems
  	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```

Anyway, @IAPark we should probably drop 2.7 support since it's EOL and `rb-sys` will

**Comment by ianks** [comment]
@IAPark just saw you are looking for maintainership help. Happy to lend a hand here if you send inv ❤️

**Comment by gjtorikian** [comment]
Thanks y'all.

**Pull request merged**
